from libcamera import controls

# DEFAULT_IMAGES_DIR = "/media/pi/data1/Images/"
# DEFAULT_IMAGES_DIR = "/home/pi/Workspace/Python/PyCharm/PiCamera/PyQt6/Raspi5/PiCamRasp5Qt6_1/Images"
DEFAULT_IMAGES_DIR = "/home/pi/Pictures/Camera/Images"

# DEFAULT_CONFIGURATION_FILE = "/media/pi/data1/Configuration/configuration.ini"
DEFAULT_CONFIGURATION_FILE = "configuration.ini"
DEFAULT_FILES_INDEX_CONFIGURATION_FILE = "indexes.ini"

FOCUS_CENTER_WIDTH = 100
FOCUS_CENTER_HEIGHT = 100

FOCUS_TYPE_NONE = 0
FOCUS_TYPE_CENTER_50X50 = 1
FOCUS_TYPE_CENTER_100X100 = 2
FOCUS_TYPE_CENTER_200X200 = 3

# Define what is the exposure level that above it exposure beeps may be enabled
EXPOSURE_BEEPS_MIN_EXPOSURE_VALUE = 250000  # Only if exp. time >= 0.25sec

# Usd for sending file management messages.
# Do not change the #x prefix!
DEFAULT_IMAGES_DIR_MSSG = "#D" + DEFAULT_IMAGES_DIR  # /media/pi/data1/Images/"
DEFAULT_IMAGE_FILE_NAME_MSSG = "#Fimage"
DEFAULT_IMAGE_FILE_EXTENSION_MSSG = "#E.jpg"

# Used for sending information messages
# Do not change the #xxxx prefix
DEFAULT_CHARGING_STATUS = "CHRG0"
DEFAULT_BAT_CAPACITY = "#BATC99"
DEFAULT_BAT_VOLTAGE = "#BATV4.02"
DEFAULT_CAMERA_ON_TIME = "#TIMO01:21:45"
DEFAULT_CPU_TEMP = "#CTMP65"
DEFAULT_CPU_USAGE = "#CUSE48"
DEFAULT_CAMERA_LUX = "#LUXD10000"
DEFAULT_CAMERA_GAIN = "#CAMG010"
DEFAULT_CAMERA_EXP_TIME = "#CAME10000000"
DEFAULT_CAMERA_FOCUS = "CAMFC100"

# Used for sending camera control messages.
# do not change the #CAMxxxyyy prefix
DEFAULT_CAMERA_CONTROL_AGC_MODE = "#CAMAGCMOD000"
DEFAULT_CAMERA_CONTROL_AGC_CONSTRAINT_MODE = "#CAMAGGCON000"
DEFAULT_CAMERA_CONTROL_AGC_EXPOSURE_MODE = "#CAMAGCEXP000"
DEFAULT_CAMERA_CONTROL_EXPOSURE_TIME = "#CAMEXPTIM000"
DEFAULT_CAMERA_CONTROL_GAIN = "#CAMEXPGIN000"
DEFAULT_CAMERA_CONTROL_EXPOSURE_COMPENSATION = "#CAMEXPCMP000"
DEFAULT_CAMERA_CONTROL_AGC_METERING_MODE = "#CAMAGCMET000"

DEFAULT_CAMERA_CONTROL_AWB_ENABLE = "#CAMAWBENA000"
DEFAULT_CAMERA_CONTROL_WB_MODE = "#CAMWBMODE000"
DEFAULT_CAMERA_CONTROL_SATURATION = "#CAMCONSAT010"  # 010 (01.0)   320 (32.0)
DEFAULT_CAMERA_CONTROL_SHARPNESS = "#CAMSHARPN000"
DEFAULT_CAMERA_CONTROL_NOISE_REDUCTION_MODE = "#CAMNOISEM000"
DEFAULT_CAMERA_CONTROL_CONTRAST = "#CAMCONTRS000"
DEFAULT_CAMERA_CONTROL_BRIGHTNESS = "#CAMBRIGHT000"
DEFAULT_CAMERA_CONTROL_QUALITY = "CAMQUALIT000"

DEFAULT_CAMERA_CONTROL_SHOOT_DELAY = "#CAMSHTDEL000"
DEFAULT_CAMERA_CONTROL_SHOOT_DELAY_BEEPS = "#CAMSHDLBP000"
DEFAULT_CAMERA_CONTROL_EXPOSURE_BEEPS = "#CAMEXPBPS000"

DEFAULT_CAMERA_CONTROL_FLASH_MODE = "#CAMFLSHMD000"
DEFAULT_CAMERA_CONTROL_FLASH_DELAY = "#CAMFLSHDL000"

DEFAULT_CAMERA_CONTROL_PREVIEW_FPS = "#CAMPRVFPS000"

DEFAULT_CAMERA_CONTROL_PIC_TRANSFORM = "#CAMTRANSF000"

ACTIVE_SLIDER_NONE = 0
ACTIVE_SLIDER_EXPOSURE_TIME = 1
ACTIVE_SLIDER_EXPOSURE_COMPENSATION = 2
ACTIVE_SLIDER_SATURATION = 3
ACTIVE_SLIDER_CONTRAST = 4
ACTIVE_SLIDER_BRIGHTNESS = 5
ACTIVE_SLIDER_SHARPNESS = 6
ACTIVE_SLIDER_GAIN = 7

HW_INFO_UPDATE_RATE_SEC = 1

white_balance_modes = {
    "000": controls.AwbModeEnum.Auto,
    "001": controls.AwbModeEnum.Tungsten,
    "002": controls.AwbModeEnum.Fluorescent,
    "003": controls.AwbModeEnum.Indoor,
    "004": controls.AwbModeEnum.Daylight,
    "005": controls.AwbModeEnum.Cloudy,
    "006": controls.AwbModeEnum.Custom
}

noise_reduction_modes = {
    "000": controls.draft.NoiseReductionModeEnum.Off,
    "001": controls.draft.NoiseReductionModeEnum.Fast,
    "002": controls.draft.NoiseReductionModeEnum.HighQuality
}

auto_exposure_constraints_modes = {
    "000": controls.AeConstraintModeEnum.Normal,
    "001": controls.AeConstraintModeEnum.Highlight,
    "002": controls.AeConstraintModeEnum.Shadows,
    "003": controls.AeConstraintModeEnum.Custom
}

auto_exposure_modes = {
    "000": controls.AeExposureModeEnum.Normal,
    "001": controls.AeExposureModeEnum.Short,
    "002": controls.AeExposureModeEnum.Long,
    "003": controls.AeExposureModeEnum.Custom
}

auto_exposure_metering_mode = {
    "000": controls.AeMeteringModeEnum.CentreWeighted,
    "001": controls.AeMeteringModeEnum.Spot,
    "002": controls.AeMeteringModeEnum.Matrix,
    "003": controls.AeMeteringModeEnum.Custom
}

exposure_display_values = ["8000", "6400", "5000", "4000", "3200",
                           "2500", "2000", "1600", "1250", "1000",
                           "800", "640", "500", "400", "320",
                           "250", "200", "160", "125", "100",
                           "80", "60", "50", "40", "30",
                           "25", "20", "15", "13", "10",
                           "8", "6", "5", "4", "0''3",
                           "0''4", "0''5", "0''6", "0''8", "1''",
                           "1''3", "1''6", "2''", "2''5", "3''2",
                           "4''", "5''", "6''", "8''", "10''",
                           "13''", "15''", "20''", "25''", "30''"]

# Exposure time in usec
exposure_time_values = {
    "000": 125,
    "001": 156,
    "002": 200,
    "003": 250,
    "004": 312,
    "005": 400,
    "006": 500,
    "007": 625,
    "008": 800,
    "009": 1000,
    "010": 1250,
    "011": 1563,
    "012": 2000,
    "013": 2500,
    "014": 3120,
    "015": 4000,
    "016": 5000,
    "017": 6250,
    "018": 8000,
    "019": 10000,
    "020": 12500,
    "021": 16667,
    "022": 20000,
    "023": 25000,
    "024": 33333,
    "025": 40000,
    "026": 50000,
    "027": 66667,
    "028": 76923,
    "029": 100000,
    "030": 125000,
    "031": 166667,
    "032": 200000,
    "033": 250000,
    "034": 333333,
    "035": 400000,
    "036": 500000,
    "037": 600000,
    "038": 800000,
    "039": 1000000,
    "040": 1300000,
    "041": 1600000,
    "042": 2000000,
    "043": 2500000,
    "044": 3200000,
    "045": 4000000,
    "046": 5000000,
    "047": 6000000,
    "048": 8000000,
    "049": 10000000,
    "050": 13000000,
    "051": 15000000,
    "052": 20000000,
    "053": 25000000,
    "054": 30000000
}

POWER_UP_CONFIGURATION_LAST = 0
POWER_UP_CONFIGURATION_DEFAULT = 1
DEFAULT_POWER_UP_CONFIGURATION = POWER_UP_CONFIGURATION_DEFAULT

AGC_MODE_AUTO = 0
AGC_MODE_MANUAL = 1
AGC_MODE_DEFAULT = AGC_MODE_AUTO

AGC_CONSTRAINT_MODE_NORMAL = 0
AGC_CONSTRAINT_MODE_HIGHLIGHT = 1
AGC_CONSTRAINT_MODE_SHADOWS = 2
AGC_CONSTRAINT_MODE_CUSTOM = 3
AGC_CONSTRAINT_MODE_DEFAULT = AGC_CONSTRAINT_MODE_NORMAL

AGC_EXPOSURE_MODE_NORMAL = 0
AGC_EXPOSURE_MODE_SHORT = 1
AGC_EXPOSURE_MODE_LONG = 2
AGC_EXPOSURE_MODE_CUSTOM = 3
AGC_EXPOSURE_MODE_DEFAULT = AGC_EXPOSURE_MODE_NORMAL

AGC_METERING_MODE_CENTER_WEIGHTED = 0
AGC_METERING_MODE_SPOT = 1
AGC_METERING_MODE_MATRIX = 2
AGC_METERING_MODE_CUSTOM = 3
AGC_METERING_MODE_DEFAULT = AGC_METERING_MODE_CENTER_WEIGHTED

AUTO_WHITE_BALANCE_ENABLED = 0
AUTO_WHITE_BALANCE_DISABLED = 1
AUTO_WHITE_BALANCE_EN_DIS_DEFAULT = AUTO_WHITE_BALANCE_ENABLED

WHITE_BALANCE_MODE_AUTO = 0
WHITE_BALANCE_MODE_TUNGSTEN = 1
WHITE_BALANCE_MODE_FLUORESCENT = 2
WHITE_BALANCE_MODE_INDOOR = 3
WHITE_BALANCE_MODE_DAYLIGHT = 4
WHITE_BALANCE_MODE_CLOUDY = 5
WHITE_BALANCE_MODE_CUSTOM = 6
WHITE_BALANCE_MODE_DEFAULT = WHITE_BALANCE_MODE_AUTO

NOISE_REDUCTION_MODE_OFF = 0
NOISE_REDUCTION_MODE_FAST = 1
NOISE_REDUCTION_MODE_HIGH_QUALITY = 2
NOISE_REDUCTION_MODE_DEFAULT = NOISE_REDUCTION_MODE_OFF

SHOOT_DELAY_NONE = 0
SHOOT_DELAY_2S = 1
SHOOT_DELAY_5S = 2
SHOOT_DELAY_10S = 3
SHOOT_DELAY_15S = 4
SHOOT_DELAY_DEFAULT = SHOOT_DELAY_NONE

SHOOT_DELAY_BEEPS_OFF = 0
SHOOT_DELAY_BEEPS_ONGOING = 1
SHOOT_DELAY_BEEPS_START_STOP = 2
SHOOT_DELAY_BEEPS_DEFAULT = SHOOT_DELAY_BEEPS_OFF

ON_SCREEN_PARAMS_ENABLED = 0
ON_SCREEN_PARAMS_DISABLED = 1
ON_SCREEN_PARAMS_DEFAULT = ON_SCREEN_PARAMS_ENABLED

LIVE_SETTING_ENABLED = 0
LIVE_SETTING_DISABLED = 1
LIVE_SETTING_DEFAULT = LIVE_SETTING_ENABLED

FOCUS_MEASURE_MODE_NONE = 0
FOCUS_MEASURE_MODE_CENTER_50X50 = 1
FOCUS_MEASURE_MODE_CENTER_100X100 = 2
FOCUS_MEASURE_MODE_CENTER_200X200 = 3
FOCUS_MEASURE_MODE_DEFAULT = FOCUS_MEASURE_MODE_NONE

PREVIEW_FPS_30 = 0
PREVIEW_FPS_15 = 1
PREVIEW_FPS_10 = 3
PREVIEW_FPS_STILLS = 4
PREVIEW_FPS_DEFAULT = PREVIEW_FPS_30

HISTOGRAM_DISABLED = 0
HISTOGRAM_ENABLED = 1
HISTOGRAM_DEFAULT = HISTOGRAM_DISABLED

DISPLAY_TRANSFORM_NONE = 0
DISPLAY_TRANSFORM_H_FLIP_HORIZONTAL_MIRROR = 1
DISPLAY_TRANSFORM_V_FLIP_SWAP_UP_DOWN = 2
DISPLAY_TRANSFORM_H_AND_V_FLIP_ROTATE_180 = 3
DISPLAY_TRANSFORM_DEFAULT= DISPLAY_TRANSFORM_NONE

FLASH_MODE_DISABLE = 0
FLASH_MODE_FRONT = 1
FLASH_MODE_BACK = 2
FLASH_MODE_DEFAULT = FLASH_MODE_DISABLE

FLASH_DELAY_NONE = 0
FLASH_DELAY_0_1_SEC = 1
FLASH_DELAY_0_2_SEC = 2
FLASH_DELAY_0_5_SEC = 3
FLASH_DELAY_1_SEC = 4
FLASH_DELAY_2_SEC = 5
FLASH_DELAY_5_SEC = 6
FLASH_DELAY_DEFAULT = FLASH_DELAY_NONE

WEB_SERVER_DISABLED = 0
WEB_SERVER_ENABLED = 1
WEB_SERVER_DEFAULT = WEB_SERVER_DISABLED

POWER_SAVE_TIMER_MODE_1_MIN = 0
POWER_SAVE_TIMER_MODE_2_MIN = 1
POWER_SAVE_TIMER_MODE_5_MIN = 2
POWER_SAVE_TIMER_MODE_10_MIN = 3
POWER_SAVE_TIMER_MODE_DISABLED = 4
POWER_SAVE_TIMER_MODE_DEFAULT = POWER_SAVE_TIMER_MODE_1_MIN

BEEPS_MINIMUM_TIME = 50
BEEPS_MAXIMUM_TIME = 15000

BEEPS_SEQUENCE_1_SHORT = [(BEEPS_MINIMUM_TIME, BEEPS_MINIMUM_TIME, 1)]

BEEPS_ONGOING_SEQUENCE_DELAY_2_SEC = [(BEEPS_MINIMUM_TIME, 500 - BEEPS_MINIMUM_TIME, 2),
                                      (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_ONGOING_SEQUENCE_DELAY_5_SEC = [(BEEPS_MINIMUM_TIME, 2000 - BEEPS_MINIMUM_TIME, 1),
                                      (BEEPS_MINIMUM_TIME, 500 - BEEPS_MINIMUM_TIME, 4),
                                      (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_ONGOING_SEQUENCE_DELAY_10_SEC = [(BEEPS_MINIMUM_TIME, 2000 - BEEPS_MINIMUM_TIME, 4),
                                       (BEEPS_MINIMUM_TIME, 500 - BEEPS_MINIMUM_TIME, 2),
                                       (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_ONGOING_SEQUENCE_DELAY_15_SEC = [(BEEPS_MINIMUM_TIME, 2000 - BEEPS_MINIMUM_TIME, 6),
                                       (BEEPS_MINIMUM_TIME, 500 - BEEPS_MINIMUM_TIME, 2),
                                       (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_START_STOP_SEQUENCE_DELAY_2_SEC = [(BEEPS_MINIMUM_TIME, 1000 - BEEPS_MINIMUM_TIME, 1),
                                         (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_START_STOP_SEQUENCE_DELAY_5_SEC = [(BEEPS_MINIMUM_TIME, 4000 - BEEPS_MINIMUM_TIME, 1),
                                         (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_START_STOP_SEQUENCE_DELAY_10_SEC = [(BEEPS_MINIMUM_TIME, 9000 - BEEPS_MINIMUM_TIME, 1),
                                          (1000, BEEPS_MINIMUM_TIME, 1)]

BEEPS_START_STOP_SEQUENCE_DELAY_15_SEC = [(BEEPS_MINIMUM_TIME, 14000 - BEEPS_MINIMUM_TIME, 1),
                                          (1000, BEEPS_MINIMUM_TIME, 1)]

PREVIEW_FPS_30 = 0
PREVIEW_FPS_15 = 1
PREVIEW_FPS_10 = 2
PREVIEW_FPS_5 = 4  # 3
PREVIEW_FPS_1 = 5  # 4
PREVIEW_FPS_STILLS = 3  # 5
